### ISSUE TITLE
[BUG] 使用 `--help` flag 时文本会被终端覆盖

### ISSUE THREAD

**Issue by lovemilk2333** [SourLemonJuice/WarmaShark-Roulette.TUI#1]
ENV: ![image](https://github.com/user-attachments/assets/b7f7f018-bc83-48fb-8f0d-6b8ddaccec31)

使用 `--help` flag 运行时文本会被终端覆盖, 使得文本信息无法正确识读. 期待文本输出后终端内容正常换行.

**Comment by SourLemonJuice** [comment]
应该在 https://github.com/SourLemonJuice/WarmaShark-Roulette.TUI/commit/3e68f6a70fe3b132698fc071da615c3314808654 中被修复了？
不过这应该是和特定平台的 ncurses 版本有关的，我也没有复现。
但理论上应该一点出问题的原因都没有了的说

**Comment by SourLemonJuice** [comment]
有一说一这条 issue 看着是有点过于模糊了，嗯总之 bug 看起来像这样：

```text
SHELL: $ ./warmaShark.out
SHELL: $UI game, build with ncurses.
```

可能 大概 也许 就是重复调用了两次 `endwin()` 的原因吧

关 issue 咯
